### ISSUE TITLE
Data prepare (tags)

### ISSUE THREAD

**Issue by RiceZJH** [yanbeic/VAL#2]
I got this errors when I try to run " python generate_groundtruth.py --dataset='fashion_iq' --data_path='fashion_iq' " and " python read_glove.py --dataset='fashion_iq' --data_path='datasets/fashion_iq/image_data' " :
        ...
       file = open(filename, "r")
       FileNotFoundError: [Errno 2] No such file or directory: 'datasets/fashion_iq/tags/asin2attr-test.txt'

I found the .txt in ‘datasets/fashion_iq/tags/’ should be generated by " python generate_tags.py --dataset='fashion_iq' ", but the code shows no "asin2attr-test.txt" is generated. It only generated 9 .txt as follows:
     writepaths = [
    'datasets/fashion_iq/tags/asin2attr-train-dress.txt',
    'datasets/fashion_iq/tags/asin2attr-train-shirt.txt',
    'datasets/fashion_iq/tags/asin2attr-train-toptee.txt',
    'datasets/fashion_iq/tags/asin2attr-val-dress.txt',
    'datasets/fashion_iq/tags/asin2attr-val-shirt.txt',
    'datasets/fashion_iq/tags/asin2attr-val-toptee.txt',
    'datasets/fashion_iq/tags/asin2attr-test-dress.txt',
    'datasets/fashion_iq/tags/asin2attr-test-shirt.txt',
    'datasets/fashion_iq/tags/asin2attr-test-toptee.txt',
     ]

Is there any wrong in your codes?

**Comment by yanbeic** [comment]
Hi, 
a new py file "generate_tags_fashion_iq.py" is provided in this repository to generate these files (e.g. asin2attr-train.txt, asin2attr-test.txt).

**Comment by RiceZJH** [comment]
Thank you, and I got this error:
...
file = open(filename, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/fashion_iq/captions_pairs/fashion_iq-val-cap.txt'

Again I found there is no code to generate 'fashion_iq-val-cap.txt'. This problem also exsits in "fashion200k dataset" and "shoes dataset".

**Comment by yanbeic** [comment]
Hi,
The code "generate_caption_pairs.py" has been updated accordingly to generate these files (fashion_iq-val-cap.txt and fashion_iq-train-cap.txt). The similar files for shoes (shoes-cap-train.txt and shoes-cap-test.txt) can also be generated using this code. 

On fashion200k, there is no need to generate any txt files. Once you download the fashion200k dataset, you can find a file called "test_queries.txt". Put it under the directory "datasets/fashion200k/" to run the code.

**Comment by GDam90** [comment]
Hi,
the code "generate_captions_pairs.py" still not works for fashion_iq dataset. The error is given on line 88, when it tries to open readpath[k], that happens to be a single character. To solve this issue i replaced line 79:

readpath = readpaths[p]

with

readpath = readpaths[p*3:(p+1)*3]

as far as i can understand this should fix the problem, but i would really appreciate if the author could give me a feedback. Thanks.
