### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by RiceZJH** [yanbeic/VAL#3]
When I run "python test_val.py --feature_dir=${FEAT_DIR} --batch_size=20 --dataset=fashoin_iq --subset=toptee,  I got error at Traceback (most recent call last):
  File "test_val.py", line 218, in <module>
    main()
  File "test_val.py", line 179, in main
    gt_label = order[gt_mask[i, :]]
IndexError: index 3920 is out of bounds for axis 0 with size 3920

and when the subset is "shirt", the Indexerror is: IndexError: boolean index did not match indexed array along dimension 0; dimension is 2902 but corresponding boolean dimension is 3089

when the subset is "dress", the Indexerror is: boolean index did not match indexed array along dimension 0; dimension is 2902 but corresponding boolean dimension is 2628

**Comment by yanbeic** [comment]
Did you check the size of the "gt_mask" and the size of the "dist", possible reasons are listed follow:
(1) do not have the np files for groundtruth pre-computed by "generate_groundtruth.py";
(2) do not have the right np files (query_images.npy, test_images.npy) of the extracted features.
