### ISSUE TITLE
PyTorch implementation

### ISSUE THREAD

**Issue by Cuberick-Orion** [yanbeic/VAL#4]
Hi, I know this is a bit more to ask, but just in case- is there a pyTorch implementation available, or by any chance an easy transfer of model to the pyTorch?

Thanks.

**Comment by yanbeic** [comment]
Hi David, 

Unfortunately, the current implementation is only in tensorflow. 
I understand it might be harder to use than pytorch, but currently I don't have an easy transfer to pytorch. Sorry about that.

**Comment by Cuberick-Orion** [comment]
No worries, I was just trying my luck xD. Thanks for the quick response.

**Comment by huynhtruc0309** [comment]
Hello. Are you guys have any clue to convert this code to Pytorch?
